### ISSUE TITLE
Working with Express

### ISSUE THREAD

**Issue by seanmthompson** [jvandemo/contentful-webhook-server#2]
Does this work with an existing Express application? What would the configuration for that look like?

**Comment by jvandemo** [comment]
@seanmthompson &mdash; Yes, there is a property `mountAsMiddleware` that you can use to mount the webhook server as middleware on an existing HTTP server.

It is still experimental but the code would look something like this:

``` javascript
var webhookServer = require('contentful-webhook-server')({
  username: 'user',
  password: 'pass'
});

var express = require('express');
var app = express();

app.use('/', webhookServer.mountAsMiddleware);

var server = app.listen(3000, function () {
  var host = server.address().address;
  var port = server.address().port;

  console.log('Example app listening at http://%s:%s', host, port);
});
```

Feel free to let me know how it works. It needs testing before this feature is considered stable so all feedback is welcome.

Thanks!

**Comment by dougmacklin** [comment]
Looks like this thread / repo have been inactive for a while, however I'm wondering if this express integration was ever completed? I gave it a shot, and while the webhook POST returns a successful 200, none of the code for [handling incoming webhook requests](https://github.com/jvandemo/contentful-webhook-server#handling-incoming-webhook-requests) seems to fire.

**Comment by jvandemo** [comment]
@dougmacklin &mdash; So, if I understand correctly, you see the request from Contentful coming in, but the events are not fired? Thanks!

**Comment by dougmacklin** [comment]
@jvandemo exactly! Here's my express server code (in addition, note that the `GET` route has to come before adding the middleware or it will fail, is that to be expected?):

```
const express = require('express');
const webhookServer = require('contentful-webhook-server')();

const port = process.env.PORT || 3000;

let app = express();

app.get('/', (req, res) => {
  res.send({});
});

app.use('/', webhookServer.mountAsMiddleware);

let server = app.listen(port, () => {
  console.log(`Started on port ${port}`);
});

server.on('ContentManagement.ContentType.publish', function(req){
  console.log('A content type was published!');
});

server.on('ContentManagement.ContentType.unpublish', function(req){
  console.log('A content type was unpublished!');
});

server.on('ContentManagement.Entry.publish', function(req){
  console.log('An entry was published!');
});

server.on('ContentManagement.Entry.unpublish', function(req){
  console.log('An entry was unpublished!');
});

server.on('ContentManagement.Asset.publish', function(req){
  console.log('An asset was published!');
});

server.on('ContentManagement.Asset.unpublish', function(req){
  console.log('An asset was unpublished!');
});

module.exports = app;
```

**Comment by dougmacklin** [comment]
Doing some testing with a local version of your [server.js](https://github.com/jvandemo/contentful-webhook-server/blob/master/lib/server.js) file and have confirmed that the events are definitely being emitted, however setting a variable equal to `app.listen()` like

```
let server = app.listen(port, () => {
  console.log(`Started on port ${port}`);
});
```

and then listening for events

```
server.on('ContentManagement.Entry.publish', (req) => {
  console.log(req);
});
```

doesn't seem to be receiving the emitted events 🤔

**Comment by jvandemo** [comment]
@dougmacklin &mdash; You must listen on the `webhookServer`, not on `server`.

I have added an example [right here](https://github.com/jvandemo/contentful-webhook-server/blob/master/examples/webhook-server-as-express-app.js).

Can you let me know if that works for you? Thanks!

**Comment by dougmacklin** [comment]
@jvandemo ah that does the trick, thanks!

**Comment by jvandemo** [comment]
@dougmacklin &mdash; Awesome, thanks for the confirmation 👍
