### ISSUE TITLE
What is in the webhook request?

### ISSUE THREAD

**Issue by rossthedevigner** [jvandemo/contentful-webhook-server#3]
I wasn't able to find any documentation on Contentful, but exactly does the request contain after an entry has been published? I'm curious to know if it contains the actual record IDs and content-types for each publish event.

**Comment by jvandemo** [comment]
@rossthedevigner &mdash; The documentation [can be found here](https://www.contentful.com/developers/docs/references/content-management-api/#/reference/webhooks).

I will close this issue but feel free to re-open it if you think the documentation does not answer your question.

Thanks and have a great weekend!
